# Config file for automatic testing at travis-ci.org

sudo: required
dist: xenial
language: python
cache: pip

addons:
    firefox: latest
    chrome: stable

matrix:
    fast_finish: true
    include:
        - os: linux
        python: 3.6
        env: TOXENV=py36
        - os: linux
        python: 3.7
        env: TOXENV=py37
        - os: linux
        python: 3.8
        env: TOXENV=py38
        # TODO: SQlite errors, e.g.: https://travis-ci.org/github/jedie/django-for-runners/jobs/663624080
        #- os: linux
        #  python: pypy3
        # TODO:
        #- os: osx
        #  language: generic

before_install:
    #
    # install Chromium Browser + Selenium WebDriver for it:
    - sudo apt-get update
    - sudo apt-get install chromium-browser chromium-chromedriver
    #
    # install Selenium Firefox WebDriver 'geckodriver':
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz -O geckodriver.tar.gz
    - mkdir $PWD/geckodriver
    - tar -xvf geckodriver.tar.gz -C $PWD/geckodriver
    - ls -la $PWD/geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - geckodriver --version

install:
    - pip3 install poetry
    - make install
    - poetry run pip freeze
    - make tox-listenvs

script:
    - if [ "$TOXENV" == "" ]; then make pytest; fi
    - if [ "$TOXENV" != "" ]; then make tox; fi
    - if [ "$TOXENV" != "" ]; then make lint; fi

after_success:
    - coveralls
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)
